### ISSUE TITLE
Converter Won't Load: NSAppTransportSecurity

### ISSUE THREAD

**Issue by organnoise** [facebookincubator/facebook-360-spatial-workstation#3]
Pro Tools Ultimate 2019.6 , El Capitan, Macbook Mid-2012

Convertor only loads this text:

The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

[https://scontent.fybz2-1.fna.fbcdn.net/v/t1.0-9/41799527_10215768792480109_6059008637613899776_n.jpg?_nc_cat=109&_nc_oc=AQnyG8Vz7IDg1SMfd_2m81u2jzrTD0ZQpBHK-F0s4BT4CAi6olABrO_ByDrGMwjVZUQ&_nc_ht=scontent.fybz2-1.fna&oh=46fc4328fc8f86c6c1ea97310d443eb8&oe=5E02009F](url)

**Comment by re-sounding** [comment]
Closing since this issue has a follow up on the FB360 Spatial Workstation Facebook group (please use that group for future reports).
