### ISSUE TITLE
Maximum Audio Source Number Limitation?

### ISSUE THREAD

**Issue by averysi224** [facebookincubator/facebook-360-spatial-workstation#7]
Hi,

May I ask if there's a maximum Audio source limitation for this workstation? If yes, what's the number and is it because of the computational limitation?

Thanks!

**Comment by weichunyuan** [comment]
Sorry to be late. This is a value controlled at Engine initialization, not hardcoded. You can change that based on performance and measurement of your implementation. At the AudioEngine initialization, we would have have to pass in the objectPoolSize, you can set it as needed. The following code snippet shows how you can use it.

    public class FBAudio360Bootstrapper : BootstrapperBase<FBAudio360Bootstrapper>
    {
        protected override void Awake()
        {
            if (init)
            {
                return;
            }

            const int objectPoolSize = 64;
            const int spatFilePoolSize = 4;
            const int spatQueuePoolSize = 2;
            InitInternal(
                RuntimeOptions.CreateLegacy(objectPoolSize, spatFilePoolSize, spatQueuePoolSize), 
                Utils.kEngineSampleRate,
                AudioDeviceType.DEFAULT);
        }
....
}
